---
- name: Gather facts
  ansible.builtin.gather_facts: {}

- name: Install desktop environment
  become: true
  ansible.builtin.dnf:
    name: '@kde-desktop-environment'
  when: kah_env_use_kde
  tags:
    - desktop

- name: Add VirtualBox repo key
  become: true
  ansible.builtin.rpm_key:
    key: https://www.virtualbox.org/download/oracle_vbox.asc
    state: present
  when: kah_env_use_virtualbox
  tags:
    - virtualbox

- name: Add VirtualBox repo
  become: true
  ansible.builtin.yum_repository:
    name: virtualbox
    description: VirtualBox
    baseurl: http://download.virtualbox.org/virtualbox/rpm/fedora/36/$basearch
    gpgcheck: true
    gpgkey: https://www.virtualbox.org/download/oracle_vbox.asc
  when: kah_env_use_virtualbox
  tags:
    - virtualbox

- name: Add tailscale repo key
  become: true
  ansible.builtin.rpm_key:
    key: https://pkgs.tailscale.com/stable/fedora/repo.gpg
    state: present
  when: kah_env_use_tailscale
  tags:
    - tailscale

- name: Add tailscale repo
  become: true
  ansible.builtin.yum_repository:
    name: tailscale-stable
    description: Tailscale stable
    baseurl: https://pkgs.tailscale.com/stable/fedora/$basearch
    gpgcheck: false
    repo_gpgcheck: true
    gpgkey: https://pkgs.tailscale.com/stable/fedora/repo.gpg
  when: kah_env_use_tailscale
  tags:
    - tailscale

- name: Install tailscale
  become: true
  ansible.builtin.dnf:
    name: tailscale
  when: kah_env_use_tailscale
  tags:
    - tailscale

- name: Add VS Code repo key
  become: true
  ansible.builtin.rpm_key:
    key: https://packages.microsoft.com/keys/microsoft.asc
    state: present
  tags:
    - packages

- name: Add VS Code repo
  become: true
  ansible.builtin.yum_repository:
    name: code
    description: Visual Studio Code
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    gpgcheck: true
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    file: vscode
  tags:
    - packages

- name: Remove microshift repo
  become: true
  community.general.copr:
    name: '@redhat-et/microshift'
    state: absent

- name: Remove microshift RPM
  become: true
  ansible.builtin.dnf:
    name: microshift
    state: absent

- name: Remove browser RPMs
  become: true
  ansible.builtin.dnf:
    name:
      - firefox
      - google-chrome-stable
    state: absent
  when: kah_env_use_flatpak_browsers

- name: Install packages
  become: true
  ansible.builtin.dnf:
    name:
      - '@Development Tools'
      - android-tools
      - ansible
      - ansible-lint
      - asciinema
      - bat
      - black
      - buildah
      - cabextract
      - clang
      - cmake
      - code
      - direnv
      - dnf-automatic
      - docker-compose
      - dotnet
      - git
      - golang
      - gtk3-devel
      - hadolint
      - httpie
      - innoextract
      - java-17-openjdk-devel
      - jq
      - kernel-devel
      - lutris
      - mediawriter
      - meld
      - moby-engine
      - mono-devel
      - ncdu
      - ninja-build
      - nmap
      - nodejs
      - nodejs-npm
      - okteta
      - okular
      - openssl
      - opentofu
      - osbuild-selinux
      - pandoc
      - pipx
      - podman
      - podman-compose
      - poetry
      - pre-commit
      - procps-ng
      - protobuf-compiler
      - protobuf-devel
      - python3-ansible-lint
      - python3-netaddr
      - qrencode
      - rclone
      - retroarch
      - ripgrep
      - rustup
      - skopeo
      - syncthing
      - task
      - tig
      - tlp
      - vim
      - virt-manager
      - wireguard-tools
      - wl-clipboard
      - yakuake
      - yamllint
      - yubikey-manager
    state: present
  tags:
    - packages

- name: Add flathub
  become: true
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
  tags:
    - flatpaks

- name: Install flatpaks
  become: true
  community.general.flatpak:
    name:
      - ch.theologeek.Manuskript
      - com.discordapp.Discord
      - com.spotify.Client
      - com.valvesoftware.Steam
      - net.cozic.joplin_desktop
      - org.videolan.VLC
      - us.zoom.Zoom
  tags:
    - flatpaks

- name: Install browsers via flatpak
  become: true
  community.general.flatpak:
    name:
      - com.google.Chrome
      - org.chromium.Chromium
      - org.mozilla.firefox
  when: kah_env_use_flatpak_browsers
  tags:
    - flatpaks

- name: Enable automatic dnf updates
  become: true
  ansible.builtin.systemd:
    name: dnf-automatic-install
    enabled: true
  when: kah_env_use_dnf_auto

- name: Start docker service
  become: true
  ansible.builtin.systemd:
    name: docker
    enabled: true
    state: started

- name: Add user to groups
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups:
      - docker
      - libvirt
    append: true
  tags:
    - user

- name: Create autostart directory
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/autostart"
    state: directory
  tags:
    - user

- name: Set yakuake to autostart
  ansible.builtin.file:
    src: /usr/share/applications/org.kde.yakuake.desktop
    dest: "{{ ansible_user_dir }}/.config/autostart/org.kde.yakuake.desktop"
    state: link
  when: kah_env_use_yakuake
  tags:
    - user

- name: Create linuxbrew system user
  become: true
  ansible.builtin.user:
    name: linuxbrew
    system: true
  when: kah_env_use_brew
  tags:
    - brew

- name: Create homebrew home directory
  become: true
  ansible.builtin.file:
    path: /home/linuxbrew/.linuxbrew
    state: directory
    owner: linuxbrew
    group: linuxbrew
  when: kah_env_use_brew
  tags:
    - brew

- name: Create homebrew /opt directory
  become: true
  ansible.builtin.file:
    path: /opt/linuxbrew
    state: directory
  when: (kah_env_use_brew and '/home' is link)
  tags:
    - brew

- name: Create homebrew config directory
  become: true
  ansible.builtin.file:
    path: /etc/homebrew
    state: directory
  when: (kah_env_use_brew and '/home' is link)
  tags:
    - brew

# workaround issue where brew gets confused in systems having /var/home symlinks
- name: Create brew.env config file
  become: true
  ansible.builtin.copy:
    content: |
      HOMEBREW_REPOSITORY=/home/linuxbrew/.linuxbrew
      HOMEBREW_CELLAR=/home/linuxbrew/.linuxbrew/Cellar
    dest: /etc/homebrew/brew.env
  when: (kah_env_use_brew and '/home' is link)
  tags:
    - brew

- name: Create symlink to brew directory
  become: true
  ansible.builtin.file:
    src: /opt/linuxbrew
    dest: /home/linuxbrew/.linuxbrew
    owner: linuxbrew
    group: linuxbrew
    state: link
  when: (kah_env_use_brew and '/home' is link)
  tags:
    - brew

- name: Create tmpfiles entry for linuxbrew symlink
  become: true
  ansible.builtin.copy:
    content: 'L /home/linuxbrew/.linuxbrew - - - - /opt/linuxbrew'
    dest: /etc/tmpfiles.d/linuxbrew.conf
  when: (kah_env_use_brew and '/home' is link)
  tags:
    - brew

- name: Download homebrew.tar.gz
  become: true
  ansible.builtin.get_url:
    url: https://github.com/Homebrew/brew/archive/refs/tags/4.3.5.tar.gz
    dest: /opt/homebrew.tar.gz
    checksum: sha256:484b5ec9e568dcf991bf79fecdf77856b722af03f6fbdc6f8f9ef45d212c9b08
  when: kah_env_use_brew
  tags:
    - brew

- name: Unpack homebrew
  become: true
  ansible.builtin.unarchive:
    src: /opt/homebrew.tar.gz
    dest: /home/linuxbrew/.linuxbrew
    owner: linuxbrew
    group: linuxbrew
    remote_src: true
    creates: /home/linuxbrew/.linuxbrew/bin/brew
    extra_opts:
      - --strip-components=1
  when: kah_env_use_brew
  tags:
    - brew

- name: Setup homebrew taps
  become: true
  become_user: linuxbrew
  community.general.homebrew_tap:
    name:
      - aquasecurity/trivy
      - quarkusio/tap
  when: kah_env_use_brew
  tags:
    - brew

- name: Install homebrew packages
  become: true
  become_user: linuxbrew
  community.general.homebrew:
    name:
      - aquasecurity/trivy/trivy
      - argocd
      - chezmoi
      - dive
      - geckodriver
      - helm
      - k3d
      - k9s
      - kind
      - kube-linter
      - minikube
      - openshift-cli
      - operator-sdk
      - quarkusio/tap/quarkus
      - sops
      - starship
      - stern
      - vale
      - yq
  when: kah_env_use_brew
  tags:
    - brew

- name: Download bundletool.jar
  become: true
  ansible.builtin.get_url:
    url: https://github.com/google/bundletool/releases/download/{{ bundletool }}/bundletool-all-{{ bundletool }}.jar
    dest: /usr/local/bin/bundletool.jar
  tags:
    - misc-software

- name: Install bundletool wrapper
  become: true
  ansible.builtin.copy:
    content: |
      #!/bin/bash
      java -jar /usr/local/bin/bundletool.jar "$@"
    dest: /usr/local/bin/bundletool
    mode: '0755'
  tags:
    - misc-software

- name: Download ollama
  become: true
  ansible.builtin.get_url:
    url: https://github.com/ollama/ollama/releases/download/{{ ollama }}/ollama-linux-amd64
    mode: '0755'
    dest: /usr/local/bin/ollama
  tags:
    - misc-software

- name: Create ollama system user
  become: true
  ansible.builtin.user:
    name: ollama
    system: true
  tags:
    - misc-software

- name: Set up ollama systemd unit
  become: true
  ansible.builtin.copy:
    src: ollama.service
    dest: /etc/systemd/system/ollama.service
  tags:
    - misc-software
  notify:
    systemd-reload

- name: Start/enable ollama
  become: true
  ansible.builtin.systemd:
    name: ollama
    enabled: true
    state: started
  tags:
    - misc-software

- name: Create dir for quarto
  become: true
  ansible.builtin.file:
    path: /opt/quarto
    state: directory
  tags:
    - misc-software

- name: Download quarto
  become: true
  ansible.builtin.unarchive:
    src: https://github.com/quarto-dev/quarto-cli/releases/download/{{ quarto }}/quarto-{{ quarto | replace('v', '') }}-linux-amd64.tar.gz
    dest: /opt/quarto
    remote_src: true
    extra_opts:
      - --strip-components=1
  tags:
    - misc-software

- name: Download crc
  become: true
  ansible.builtin.unarchive:
    src: "https://developers.redhat.com/content-gateway/file/pub/openshift-v4/clients/crc/{{ crc | replace('v', '') }}/crc-linux-amd64.tar.xz"
    dest: /usr/local/bin/
    include: [ "crc-linux-{{ crc | replace('v', '') }}-amd64/crc" ]
    remote_src: true
    extra_opts:
      - --strip-components=1
  tags:
    - misc-software

- name: Copy versions.yaml to /usr/local/bin
  become: true
  ansible.builtin.copy:
    src: versions.yaml
    dest: /usr/local/bin/versions.yaml
  tags:
    - misc-software

- name: Configure environment
  become: true
  ansible.builtin.copy:
    src: kahowell-environment.sh
    dest: /etc/profile.d/kahowell-environment.sh
  tags:
    - global-config

- name: Install python tools
  become: true
  community.general.pipx:
    name: "{{ item }}"
    install_deps: true
  environment:
    PIPX_HOME: /opt/pipx
    PIPX_BIN_DIR: /usr/local/bin
    PIPX_MAN_DIR: /usr/local/share/man
  with_items:
    - crc-bonfire
    - mkdocs-techdocs-core
    - mitmproxy
  tags:
    - misc-software
    - python

- name: Install nodejs tools
  become: true
  community.general.npm:
    name: "{{ item }}"
    global: true
  with_items:
    - markdownlint-cli2
  tags:
    - misc-software
    - nodejs
