---
- name: Gather facts
  ansible.builtin.gather_facts: {}

- name: Install desktop environment
  become: true
  ansible.builtin.dnf:
    name: '@kde-desktop-environment'
  when: kah_env_use_kde
  tags:
    - desktop

- name: Add VirtualBox repo key
  become: true
  ansible.builtin.rpm_key:
    key: https://www.virtualbox.org/download/oracle_vbox.asc
    state: present
  when: kah_env_use_virtualbox
  tags:
    - virtualbox

- name: Add VirtualBox repo
  become: true
  ansible.builtin.yum_repository:
    name: virtualbox
    description: VirtualBox
    baseurl: http://download.virtualbox.org/virtualbox/rpm/fedora/36/$basearch
    gpgcheck: true
    gpgkey: https://www.virtualbox.org/download/oracle_vbox.asc
  when: kah_env_use_virtualbox
  tags:
    - virtualbox

- name: Add tailscale repo key
  become: true
  ansible.builtin.rpm_key:
    key: https://pkgs.tailscale.com/stable/fedora/repo.gpg
    state: present
  when: kah_env_use_tailscale
  tags:
    - tailscale

- name: Add tailscale repo
  become: true
  ansible.builtin.yum_repository:
    name: tailscale-stable
    description: Tailscale stable
    baseurl: https://pkgs.tailscale.com/stable/fedora/$basearch
    gpgcheck: false
    repo_gpgcheck: true
    gpgkey: https://pkgs.tailscale.com/stable/fedora/repo.gpg
  when: kah_env_use_tailscale
  tags:
    - tailscale

- name: Install tailscale
  become: true
  ansible.builtin.dnf:
    name: tailscale
  when: kah_env_use_tailscale
  tags:
    - tailscale

- name: Add VS Code repo key
  become: true
  ansible.builtin.rpm_key:
    key: https://packages.microsoft.com/keys/microsoft.asc
    state: present
  tags:
    - packages

- name: Add VS Code repo
  become: true
  ansible.builtin.yum_repository:
    name: code
    description: Visual Studio Code
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    gpgcheck: true
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    file: vscode
  tags:
    - packages

- name: Remove microshift repo
  become: true
  community.general.copr:
    name: '@redhat-et/microshift'
    state: absent

- name: Remove microshift RPM
  become: true
  ansible.builtin.dnf:
    name: microshift
    state: absent

- name: Remove browser RPMs
  become: true
  ansible.builtin.dnf:
    name:
      - firefox
      - google-chrome-stable
    state: absent
  when: kah_env_use_flatpak_browsers

- name: Install packages
  become: true
  ansible.builtin.dnf:
    name:
      - '@Development Tools'
      - android-tools
      - ansible
      - ansible-lint
      - asciinema
      - bat
      - black
      - clang
      - cmake
      - code
      - direnv
      - dnf-automatic
      - docker-compose
      - dotnet
      - git
      - golang
      - gtk3-devel
      - hadolint
      - java-17-openjdk-devel
      - jq
      - kernel-devel
      - meld
      - moby-engine
      - mono-devel
      - ncdu
      - ninja-build
      - nmap
      - nodejs
      - openssl
      - podman
      - podman-compose
      - poetry
      - pre-commit
      - procps-ng
      - protobuf-compiler
      - python3-ansible-lint
      - python3-netaddr
      - rclone
      - ripgrep
      - syncthing
      - task
      - tig
      - tlp
      - vim
      - virt-manager
      - wireguard-tools
      - wl-clipboard
      - yakuake
      - yamllint
      - yubikey-manager
    state: present
  tags:
    - packages

- name: Add flathub
  become: true
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
  tags:
    - flatpaks

- name: Install flatpaks
  become: true
  community.general.flatpak:
    name:
      - ch.theologeek.Manuskript
      - com.discordapp.Discord
      - com.spotify.Client
      - com.valvesoftware.Steam
      - net.cozic.joplin_desktop
      - org.videolan.VLC
      - us.zoom.Zoom
  tags:
    - flatpaks

- name: Install browsers via flatpak
  become: true
  community.general.flatpak:
    name:
      - com.google.Chrome
      - org.chromium.Chromium
      - org.mozilla.firefox
  when: kah_env_use_flatpak_browsers
  tags:
    - flatpaks

- name: Enable automatic dnf updates
  become: true
  ansible.builtin.systemd:
    name: dnf-automatic-install
    enabled: true
  when: kah_env_use_dnf_auto

- name: Start docker service
  become: true
  ansible.builtin.systemd:
    name: docker
    enabled: true
    state: started

- name: Add user to groups
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups:
      - docker
      - libvirt
    append: true
  tags:
    - user

- name: Create autostart directory
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/autostart"
    state: directory
  tags:
    - user

- name: Set yakuake to autostart
  ansible.builtin.file:
    src: /usr/share/applications/org.kde.yakuake.desktop
    dest: "{{ ansible_user_dir }}/.config/autostart/org.kde.yakuake.desktop"
    state: link
  when: kah_env_use_yakuake
  tags:
    - user

- name: Download homebrew install script
  become: true
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/Homebrew/install/3e7999a7fb0e8f38248d61d081893a628d7b6885/install.sh
    dest: /opt/install-homebrew.sh
    checksum: sha256:41d5eb515a76b43e192259fde18e6cd683ea8b6a3d7873bcfc5065ab5b12235c
  when: kah_env_use_brew
  tags:
    - brew

- name: Run homebrew installer
  ansible.builtin.command: bash -c 'NONINTERACTIVE=1 bash /opt/install-homebrew.sh'
  args:
    creates: /home/linuxbrew/.linuxbrew/bin/brew
  when: kah_env_use_brew
  tags:
    - brew

- name: Setup homebrew taps
  community.general.homebrew_tap:
    name:
      - aquasecurity/trivy
      - quarkusio/tap
  when: kah_env_use_brew
  tags:
    - brew

- name: Install homebrew packages
  community.general.homebrew:
    name:
      - aquasecurity/trivy/trivy
      - argocd
      - chezmoi
      - dive
      - geckodriver
      - helm
      - k3d
      - k9s
      - kind
      - kube-linter
      - markdownlint-cli2
      - minikube
      - openshift-cli
      - operator-sdk
      - quarkusio/tap/quarkus
      - rustup-init
      - sops
      - starship
      - stern
      - vale
      - yq
  when: kah_env_use_brew
  tags:
    - brew
