---
- name: Gather facts
  ansible.builtin.gather_facts: {}

- name: Install homebrew
  ansible.builtin.include_tasks: "install-brew.yaml"
  when: ansible_pkg_mgr=="dnf5"  # assumed to be ublue-based otherwise

- name: Install RPMs
  ansible.builtin.include_tasks: "install-rpms.yaml"
  when: ansible_pkg_mgr=="dnf5"  # assumed to be ublue-based otherwise

- name: Setup CUDA
  ansible.builtin.include_tasks: "setup-cuda.yaml"
  when: (ansible_pkg_mgr=="dnf5" and kah_env_use_cuda)

- name: Setup homebrew taps
  become: "{{ ansible_pkg_mgr=='dnf5' }}"
  become_user: "{{ 'linuxbrew' if ansible_pkg_mgr=='dnf5' else '' }}"
  community.general.homebrew_tap:
    name:
      - aquasecurity/trivy
      - get-woke/tap
      - metalbear-co/mirrord
      - quarkusio/tap
      - telepresenceio/telepresence
  tags:
    - brew

- name: Install homebrew casks
  become: "{{ ansible_pkg_mgr=='dnf5' }}"
  become_user: "{{ 'linuxbrew' if ansible_pkg_mgr=='dnf5' else '' }}"
  community.general.homebrew_cask:
    name:
      # general tools
      - android-platform-tools
      - claude-code
    path: "{{ ansible_env['HOMEBREW_PREFIX'] | default('/home/linuxbrew/.linuxbrew') }}/bin"
  tags:
    - brew

- name: Install homebrew packages
  become: "{{ ansible_pkg_mgr=='dnf5' }}"
  become_user: "{{ 'linuxbrew' if ansible_pkg_mgr=='dnf5' else '' }}"
  community.general.homebrew:
    name:
      # general tools
      - bw
      - fd
      - fzf
      - git-delta
      - innoextract
      - pandoc
      - syncthing
      - wakeonlan
      # general dev tools
      - atuin
      - bash-preexec
      - chezmoi
      - direnv
      - eza
      - geckodriver
      - get-woke/tap/woke
      - gh
      - gitleaks
      - grpcurl
      - httpie
      - markdownlint-cli2
      - mermaid-cli
      - nmap
      - nvm
      - pnpm
      - pre-commit
      - protobuf
      - qsv
      - sops
      - starship
      - trufflehog
      - vale
      - yamllint
      - yq
      # devops/automation tools
      - ansible
      - ansible-lint
      - opentofu
      # cli tools
      - asciinema
      - bat
      - ncdu
      - qrencode
      - rclone
      - rich-cli
      - ripgrep
      - task
      - tig
      # python tools
      - black
      - poetry
      - uv
      # dotnet tools
      - dotnet
      # golang tools
      - go
      - golangci-lint
      # java tools
      - openjdk
      - quarkusio/tap/quarkus
      # node js tools
      - node
      # rust tools
      - rustup
      # k8s tools
      - aquasecurity/trivy/trivy
      - argocd
      - dive
      - helm
      - k3d
      - k9s
      - kind
      - kube-linter
      - kubebuilder
      - kubelogin
      - kustomize
      - kwok
      - minikube
      - mirrord
      - ocm
      - openshift-cli
      - operator-sdk
      - rosa-cli
      - stern
      - telepresence-oss
      # ai tools
      - mcp-toolbox
      - ollama
      - opencode
      - repomix
      - specify
  tags:
    - brew

- name: Add flathub
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
  tags:
    - flatpak

- name: Install flatpak
  community.general.flatpak:
    name:
      - com.discordapp.Discord
      - com.google.Chrome
      - com.slack.Slack
      - com.spotify.Client
      - com.visualstudio.code
      - io.kinvolk.Headlamp
      - io.podman_desktop.PodmanDesktop
      - net.cozic.joplin_desktop
      - org.chromium.Chromium
      - org.gimp.GIMP
      - org.gnome.meld
      - org.inkscape.Inkscape
      - org.kde.okteta
      - org.mozilla.firefox
      - org.raspberrypi.rpi-imager
      - org.videolan.VLC
      - us.zoom.Zoom
  tags:
    - flatpak

- name: Install various python-based tools
  ansible.builtin.command: "uv tool install {{ item }}"
  args:
    creates: "{{ ansible_user_dir }}/.local/share/uv/tools/{{ item }}"
  with_items:
    - mitmproxy
    - openhands-ai
    - quarto-cli
  tags:
    - python
